[functions]

  [functions._ipx]
  node_bundler = "esbuild" 

  [functions.___netlify-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    "build/server/**",
    "build/serverless/**",
    "build/*.json",
    "build/BUILD_ID",
    "build/static/chunks/webpack-middleware*.js",
    "!build/server/**/*.js.nft.json",
    "!build/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "node_modules/styled-jsx/style.js",
    "./lessons/**/*.md" 
  ]
  external_node_modules = []
  node_bundler = "esbuild" 

  [functions.___netlify-odb-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    "build/server/**",
    "build/serverless/**",
    "build/*.json",
    "build/BUILD_ID",
    "build/static/chunks/webpack-middleware*.js",
    "!build/server/**/*.js.nft.json",
    "!build/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "node_modules/styled-jsx/style.js",
    "./lessons/**/*.md" 

  ]
  external_node_modules = []
  node_bundler = "esbuild" 

  [functions."_api_*"]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    "build/server/**",
    "build/serverless/**",
    "build/*.json",
    "build/BUILD_ID",
    "build/static/chunks/webpack-middleware*.js",
    "!build/server/**/*.js.nft.json",
    "!build/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "node_modules/styled-jsx/style.js",
    "./lessons/**/*.md" 

  ]
  external_node_modules = []
  node_bundler = "esbuild" 

[build]

  [build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/next.svg"
to = "/next.svg"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/vercel.svg"
to = "/vercel.svg"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/images/bandai-gashapon-machine.jpg"
to = "/images/bandai-gashapon-machine.jpg"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = true

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/_next/data/ACT8A9PLVv3WsnGCRoslt/_not-found.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_not-found"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/mathematics/form-1/:slug.rsc"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-1/:slug"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-2/:slug.rsc"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-2/:slug"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-3/:slug.rsc"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-3/:slug"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-4/:slug.rsc"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-4/:slug"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-5/:slug.rsc"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/mathematics/form-5/:slug"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[context]

  [context.production]

    [context.production.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.production.functions]

      [context.production.functions._ipx]
      node_bundler = "esbuild"

      [context.production.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "build/server/**",
        "build/serverless/**",
        "build/*.json",
        "build/BUILD_ID",
        "build/static/chunks/webpack-middleware*.js",
        "!build/server/**/*.js.nft.json",
        "!build/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js",
        "./lessons/**/*.md" 

      ]
      external_node_modules = []
      node_bundler = "esbuild"

      [context.production.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "build/server/**",
        "build/serverless/**",
        "build/*.json",
        "build/BUILD_ID",
        "build/static/chunks/webpack-middleware*.js",
        "!build/server/**/*.js.nft.json",
        "!build/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js",
        "./lessons/**/*.md" 

      ]
      external_node_modules = []
      node_bundler = "esbuild"

      [context.production.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "build/server/**",
        "build/serverless/**",
        "build/*.json",
        "build/BUILD_ID",
        "build/static/chunks/webpack-middleware*.js",
        "!build/server/**/*.js.nft.json",
        "!build/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js",
        "./lessons/**/*.md" 

      ]
      external_node_modules = []
      node_bundler = "esbuild"

    [context.production.build]

      [context.production.build.environment]
      NEXT_PRIVATE_TARGET = "server"

  [context.main]

    [context.main.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.main.functions]

      [context.main.functions._ipx]
      node_bundler = "esbuild"

      [context.main.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "build/server/**",
        "build/serverless/**",
        "build/*.json",
        "build/BUILD_ID",
        "build/static/chunks/webpack-middleware*.js",
        "!build/server/**/*.js.nft.json",
        "!build/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js",
        "./lessons/**/*.md" 

      ]
      external_node_modules = []
      node_bundler = "esbuild"

      [context.main.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "build/server/**",
        "build/serverless/**",
        "build/*.json",
        "build/BUILD_ID",
        "build/static/chunks/webpack-middleware*.js",
        "!build/server/**/*.js.nft.json",
        "!build/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js",
        "./lessons/**/*.md" 

      ]
      external_node_modules = []
      node_bundler = "esbuild"

      [context.main.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "build/server/**",
        "build/serverless/**",
        "build/*.json",
        "build/BUILD_ID",
        "build/static/chunks/webpack-middleware*.js",
        "!build/server/**/*.js.nft.json",
        "!build/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js",
        "./lessons/**/*.md" 

      ]
      external_node_modules = []
      node_bundler = "esbuild"

    [context.main.build]

      [context.main.build.environment]
      NEXT_PRIVATE_TARGET = "server"


 